apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: flux-tf-example
  namespace: infrastructure
spec:
  path: ./terraform
  interval: 5m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: flux-tf
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: ionos-token